# Generated by Django 2.2 on 2020-11-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_rank', models.IntegerField()),
                ('comment_href', models.CharField(max_length=200)),
                ('comment_title', models.CharField(max_length=100)),
                ('comment_content', models.TextField()),
                ('comment_sen', models.FloatField()),
                ('comment_id', models.TimeField()),
            ],
            options={
                'db_table': 'zdm_phone',
                'managed': False,
            },
        ),
    ]
